FROM node:12.16.1-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod

FROM nginx:1.15.8-alpine
COPY --from=build /usr/src/app/dist/nc-scripts/ /usr/share/nginx/html